### ISSUE TITLE
Enforce HTTPS - Unavailable

### ISSUE THREAD

**Issue by nicdoye** [Activiti/activiti.github.io#13]
Hi,

I hit the switch and migrated our community website for Activiti over to github pages, but can't enable SSL. How can I fix this?

Enforce HTTPS — Unavailable for your site because a certificate has not yet been issued for your domain (www.activiti.org) 

Yours,
Nic Doye

**Comment by ggrnd0** [comment]
Have another problem with
![activiti](https://user-images.githubusercontent.com/5565134/40312317-393d2d5e-5d1b-11e8-8adf-3b8b2a958e74.png)

**Comment by nicdoye** [comment]
There's HSTS on the domain. Either github fixes it or I roll back to the old site. (I could do other workarounds, but it's not my call - I'll ask the  Activiti team).

**Comment by nicdoye** [comment]
In fact, that's what you're seeing. We don't have  "Enforce HTTPS" set, because that option isn't available until they issue the certificate.

**Comment by inavarre** [comment]
Thanks so much, Nic! Really appreciate it.

That is really awful, there wasn't any warning of this happening in the docs you had shared or on the enable screen

**Comment by nicdoye** [comment]
Dear @github, as a workaround I've moved the site to Netlify. Please let me know when you have provisioned a certificate should we decide to move it back.

**Comment by bekewisdom4-beep** [comment]
> Hi,
> 
> I hit the switch and migrated our community website for Activiti over to github pages, but can't enable SSL. How can I fix this?
> 
> Enforce HTTPS — Unavailable for your site because a certificate has not yet been issued for your domain (www.activiti.org) 
> 
> Yours,
> Nic Doye
